### ISSUE TITLE
Should exactNull be exported from Data.Argonaut.JCursor?

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/purescript-argonaut-traversals#7]
Given that `Data.Argonaut.Core` already gives you `jsonNull`, can we just use that and stop exporting `exactNull`?

**Comment by garyb** [comment]
:+1:

**Comment by hdgarrood** [comment]
Oh, it's because `jsonNull :: Json` but we need a value of type `JNull`. Maybe it makes sense to put a `JNull` value inside `Data.Argonaut.Core`?
